### ISSUE TITLE
GCC 13.2 issue

### ISSUE THREAD

**Issue by devrimgunduz** [pllua/pllua#13] opened 2023-09-13 13:02 UTC
Hi,

pllua 2.0.12 fails to build against GCC 13.2 on Fedora 38. Output is below. Can you please take a look?

Thanks!

Regards, Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I%{includedir}  -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/paths.o src/paths.c
src/objects.c: In function 'pllua_resetactivation':
src/objects.c:419:22: error: too few arguments to function 'lua_resetthread'
  419 |                 rc = lua_resetthread(thread);
      |                      ^~~~~~~~~~~~~~~
In file included from src/pllua.h:19,
                 from src/objects.c:7:
/usr/include/lua.h:156:21: note: declared here
  156 | LUA_API int        (lua_resetthread) (lua_State *L, lua_State *from);
      |                     ^~~~~~~~~~~~~~~
make[1]: *** [<builtin>: src/objects.o] Error 1

**Comment by RhodiumToad** [comment] 2023-09-13 13:16
What is the Lua version, and does the Lua install have any patches applied relative to upstream?

The function `lua_resetthread` was the subject of the ABI/API break which caused Lua 5.4.5 to be superseded by 5.4.6 within days of release. Lua 5.4.5 is explicitly blacklisted (at runtime) by this package for this reason.

**Comment by RhodiumToad** [comment] 2023-09-13 13:28
Confirmed this is a bug in Fedora 38 packaging of Lua, which claims to be 5.4.4 but incorporates changes from upstream 5.4.5, including the change that broke the ABI and API.

Closing wontfix, because this is the fault of the FC Lua package maintainer, for creating a package that is incompatible with every other Lua version in existence.

**Closed as not planned** 2023-09-13 13:28 UTC

**Comment by RhodiumToad** [comment] 2023-09-14 13:04
Incidentally, you probably need to be aware that pllua binaries built against any Fedora Lua 5.4.x package from before lua-5.4.4-9 will likely crash if run against the libraries from lua-5.4.4-9 if given a query that involves early termination of a SETOF function (since in such cases lua_resetthread will be called with a single arg).

(This is why I put in code to try and detect 5.4.5 at runtime, but that doesn't help since the Fedora package still claims to be 5.4.4.)
